### ISSUE TITLE
イシューの作成(レビュー依頼)

### ISSUE THREAD

**Issue by yojiyanase** [yojiyanase/runteq_graduation_examination#7]
- [x] 下書きの作成
- [x] ストーリーポイントの設定
- [x] イシューの作成

■Webアプリの概要
ユーザーが、自分が持っているインデックスファンド（指数に連動する投資信託）の指数（S&P500など）と、毎月の積立金額（月１万円など）を選択して、過去の投資期間（1995年から1999年など）を指定すると、資産の変動がグラフで表示される（例えば、S&P５００を毎月１万円積み立てて、値動きが1990年から1995年の相場通りに動いた場合、資産の増減がどのようになるか表示する）。

■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間

■ProjectsのURL
https://github.com/users/yojiyanase/projects/2

■MVPリリースまで
- [ ] シミュレーションに使用するデータの取得機能
- [ ] 毎月定額（ドル建て）で購入した場合の金額を計算する機能
- [ ] グラフに加工する機能

■MVP後
- [ ] 日本株式市場の指数を追加(日経平均など)
- [ ] 円建てで積み立てた場合の計算機能（当時の為替レートでドルに交換して購入した場合を想定して計算する）
- [ ] 「再計算する」ボタンを押した場合に前の検索内容が表示されるように設定

■MVPレビュー依頼予定日
予定日：2024年 10月 27日

**Comment by ippei-shimizu** [comment]
概ね良いかと思います。LGTMです。
